### ISSUE TITLE
Move out-of-stock products to the end of a collection, with inventory_policy: continue

### ISSUE THREAD

**Issue by mattsodomsky** [lightward/mechanic-tasks#112]
Currently, this task looks at totalInventory to determine if a product is sold out. However, if a product variant's inventory policy is set to Continue, the front-end of Shopify doesn't show this item as sold out. The result is a mix of sold-out and technically not sold-out products at the end of the sorted collection.

From Shopify's docs: "inventory_policy - Whether customers are allowed to place an order for the product variant when it's out of stock."

In order to support looking at this field, we'd need to look at the product variants for totalInventory = 0 products.  This may not be possible without moving to bulk operations which is a significant change to the logic of this task.

**Comment by tekhaus** [comment]
To align with the manner in which Shopify displays the "Sold out" indicator on a **product** in a grid view, then this task would should check the _inventoryQuantity_ of each variant as well, since the indicator will not be displayed if a single variant has a positive inventory (or "oversell" enabled).

I don't think we need to use a bulk op for this. Decreasing the products query to the first 9 allows for the maximum of 100 variants on a product and brings the query cost to ~930 (out of 1000). The outer loop counter for the collection products would just need to be bumped up by ~x30.

```
query {
  collection(id: "gid://shopify/Collection/1234567890") {
    products(
      sortKey: ALPHA_ASC
      reverse: false
      first: 9
      after: null
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        id
        tracksInventory
        totalInventory
        variants(first: 100) {
          nodes {
            id
            inventoryPolicy
            inventoryQuantity
          }
        }
      }
    }
  }
}
```

**Comment by mattsodomsky** [comment]
Perfect sounds good! Let's proceed with this approach 😄
