### ISSUE TITLE
API deprecations reported

### ISSUE THREAD

**Issue by rajaakhtar** [lightward/mechanic-tasks#302]
https://github.com/lightward/mechanic-tasks/blob/32f4c4761706a25986c283a816d64d7d7c10b902/docs/unpublish-products-that-have-been-out-of-stock-for-x-days/script.liquid#L136

Runtime Error using the oldest supported Shopify Admin API version.

* Shopify API deprecations reported

The field Publication.name is deprecated. Use [Catalog.title](https://shopify.dev/api/admin-graphql/unstable/interfaces/Catalog#field-catalog-title) instead.

**Comment by tekhaus** [comment]
Hi @rajaakhtar, thank you for the report. This issue is being tracked in #270, and the affected tasks will be updated once there is resolution from Shopify.

For now, you can just update any tasks that report this specific deprecation to the latest API version, and the notification should disappear (until the next API release). They will continue to function properly in the meantime.
